apiVersion: magma.infra.don/v1alpha1
kind: MagmaAGW
metadata:
  name: agw-01
  namespace: magma-agw
spec:
  chart:
    repo: https://github.com/infinitydon/telco-helm-charts.git
    path: magma-agw-upstream
    version: main
    releaseName: agwc
  orc8rRef:
    name: core
    namespace: magma-system
  agwNodeSelector:
    magma.infra.don/agw: "true"
  requireDedicatedNode: true
  ueSimulator:
    enabled: false
  waitTimeoutSeconds: 1800
