apiVersion: magma.infra.don/v1alpha1
kind: MagmaOrc8r
metadata:
  labels:
    app.kubernetes.io/name: magma-operator
    app.kubernetes.io/managed-by: kustomize
  name: magma-orc8r
  namespace: magma
spec:
  releaseName: magma-fullstack
  chartPath: magma-fullstack-upstream
  domainName: magma.local
  controllerHostname: controller.magma.local
  nmsNodePort: 31316
  nmsOrganization: magma-test
  nmsAdminEmail: admin
  nmsAdminPassword: admin
  nmsCustomDomains:
    - 192.168.88.165:31316
    - 192.168.88.163:31316
    - 192.168.88.224:31316
  networkID: mpk_test
  networkName: mpk_test
  subscriberIMSI: IMSI001010000000001
