apiVersion: magma.infra.don/v1alpha1
kind: MagmaAGW
metadata:
  labels:
    app.kubernetes.io/name: magma-operator
    app.kubernetes.io/managed-by: kustomize
  name: agwc
  namespace: magma-agw
spec:
  releaseName: agwc
  chartRepository: https://github.com/infinitydon/telco-helm-charts.git
  chartRevision: main
  chartPath: magma-agw-upstream
  accessGatewayID: agw-node-02
  s1Interface: enp8s19
  sgiInterface: enp8s20
  agwNodeSelector:
    magma.io/agw-node: "true"
    kubernetes.io/hostname: ebpf-bng-node-02
  enableUERANSIM: true
  ueransimNodeSelector:
    magma.io/ueransim-node: "true"
  values:
    simulator.subscriber.provision: "true"
