apiVersion: magma.infra.don/v1alpha1
kind: MagmaOrc8r
metadata:
  name: core
  namespace: magma-system
spec:
  chart:
    repo: https://github.com/infinitydon/telco-helm-charts.git
    path: magma-fullstack-upstream
    version: main
    releaseName: magma-fullstack
  domainName: magma.local
  nms:
    serviceType: NodePort
    admin:
      organization: magma-test
      username: admin
  waitTimeoutSeconds: 3600
