//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MagmaAGW) DeepCopyInto(out *MagmaAGW) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MagmaAGW.
func (in *MagmaAGW) DeepCopy() *MagmaAGW {
	if in == nil {
		return nil
	}
	out := new(MagmaAGW)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MagmaAGW) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MagmaAGWDatapathSpec) DeepCopyInto(out *MagmaAGWDatapathSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MagmaAGWDatapathSpec.
func (in *MagmaAGWDatapathSpec) DeepCopy() *MagmaAGWDatapathSpec {
	if in == nil {
		return nil
	}
	out := new(MagmaAGWDatapathSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MagmaAGWDeletionPolicySpec) DeepCopyInto(out *MagmaAGWDeletionPolicySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MagmaAGWDeletionPolicySpec.
func (in *MagmaAGWDeletionPolicySpec) DeepCopy() *MagmaAGWDeletionPolicySpec {
	if in == nil {
		return nil
	}
	out := new(MagmaAGWDeletionPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MagmaAGWGatewayRegistrationSpec) DeepCopyInto(out *MagmaAGWGatewayRegistrationSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MagmaAGWGatewayRegistrationSpec.
func (in *MagmaAGWGatewayRegistrationSpec) DeepCopy() *MagmaAGWGatewayRegistrationSpec {
	if in == nil {
		return nil
	}
	out := new(MagmaAGWGatewayRegistrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MagmaAGWIdentitySpec) DeepCopyInto(out *MagmaAGWIdentitySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MagmaAGWIdentitySpec.
func (in *MagmaAGWIdentitySpec) DeepCopy() *MagmaAGWIdentitySpec {
	if in == nil {
		return nil
	}
	out := new(MagmaAGWIdentitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MagmaAGWList) DeepCopyInto(out *MagmaAGWList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MagmaAGW, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MagmaAGWList.
func (in *MagmaAGWList) DeepCopy() *MagmaAGWList {
	if in == nil {
		return nil
	}
	out := new(MagmaAGWList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MagmaAGWList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MagmaAGWSpec) DeepCopyInto(out *MagmaAGWSpec) {
	*out = *in
	out.Identity = in.Identity
	in.GatewayRegistration.DeepCopyInto(&out.GatewayRegistration)
	out.DeletionPolicy = in.DeletionPolicy
	if in.AGWNodeSelector != nil {
		in, out := &in.AGWNodeSelector, &out.AGWNodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.AGWNodeLabelSelector != nil {
		in, out := &in.AGWNodeLabelSelector, &out.AGWNodeLabelSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.UERANSIMNodeSelector != nil {
		in, out := &in.UERANSIMNodeSelector, &out.UERANSIMNodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.UERANSIMValidation.DeepCopyInto(&out.UERANSIMValidation)
	in.Datapath.DeepCopyInto(&out.Datapath)
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MagmaAGWSpec.
func (in *MagmaAGWSpec) DeepCopy() *MagmaAGWSpec {
	if in == nil {
		return nil
	}
	out := new(MagmaAGWSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MagmaAGWStatus) DeepCopyInto(out *MagmaAGWStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MagmaAGWStatus.
func (in *MagmaAGWStatus) DeepCopy() *MagmaAGWStatus {
	if in == nil {
		return nil
	}
	out := new(MagmaAGWStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MagmaAGWUERANSIMValidationSpec) DeepCopyInto(out *MagmaAGWUERANSIMValidationSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MagmaAGWUERANSIMValidationSpec.
func (in *MagmaAGWUERANSIMValidationSpec) DeepCopy() *MagmaAGWUERANSIMValidationSpec {
	if in == nil {
		return nil
	}
	out := new(MagmaAGWUERANSIMValidationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MagmaOrc8r) DeepCopyInto(out *MagmaOrc8r) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MagmaOrc8r.
func (in *MagmaOrc8r) DeepCopy() *MagmaOrc8r {
	if in == nil {
		return nil
	}
	out := new(MagmaOrc8r)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MagmaOrc8r) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MagmaOrc8rList) DeepCopyInto(out *MagmaOrc8rList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MagmaOrc8r, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MagmaOrc8rList.
func (in *MagmaOrc8rList) DeepCopy() *MagmaOrc8rList {
	if in == nil {
		return nil
	}
	out := new(MagmaOrc8rList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MagmaOrc8rList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MagmaOrc8rSpec) DeepCopyInto(out *MagmaOrc8rSpec) {
	*out = *in
	if in.NMSNodePort != nil {
		in, out := &in.NMSNodePort, &out.NMSNodePort
		*out = new(int32)
		**out = **in
	}
	if in.NMSCustomDomains != nil {
		in, out := &in.NMSCustomDomains, &out.NMSCustomDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MagmaOrc8rSpec.
func (in *MagmaOrc8rSpec) DeepCopy() *MagmaOrc8rSpec {
	if in == nil {
		return nil
	}
	out := new(MagmaOrc8rSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MagmaOrc8rStatus) DeepCopyInto(out *MagmaOrc8rStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MagmaOrc8rStatus.
func (in *MagmaOrc8rStatus) DeepCopy() *MagmaOrc8rStatus {
	if in == nil {
		return nil
	}
	out := new(MagmaOrc8rStatus)
	in.DeepCopyInto(out)
	return out
}
