apiVersion: v1
kind: ServiceAccount
metadata:
  name: magma-operator
  namespace: magma-operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: magma-operator
rules:
  - apiGroups: ["magma.infra.don"]
    resources: ["magmaorc8rs", "magmaagws", "magmaorc8rs/status", "magmaagws/status"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: [""]
    resources: ["namespaces", "pods", "services", "secrets", "configmaps", "events"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: magma-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: magma-operator
subjects:
  - kind: ServiceAccount
    name: magma-operator
    namespace: magma-operator-system
